export const CLIENT_ACTION = {
  CLIENT_ACTION_ADD_CLIENT: 'CLIENT_ACTION_ADD_CLIENT',
  CLIENT_ACTION_DELETE_CLIENT: 'CLIENT_ACTION_DELETE_CLIENT',
  CLIENT_ACTION_SHOW_ADD_CLIENT: 'CLIENT_ACTION_SHOW_ADD_CLIENT',
  CLIENT_ACTION_HIDDEN_ADD_CLIENT: 'CLIENT_ACTION_HIDDEN_ADD_CLIENT',
  CLIENT_ACTION_HANDLE_INFO_CLIENT: 'CLIENT_ACTION_HANDLE_INFO_CLIENT',
}

